name: compile-on-tag

on:
  push:
    tags:
      - '*'
      
jobs:
  compile-card:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile Latex document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: card.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: card.pdf
